### ISSUE TITLE
Fix Service Layer issues

### ISSUE THREAD

**Issue by ZaneBartlett1** [DartExplore/dallas-by-metro-backend#113]
This mostly has to do with correcting the GET requests with having a request body annotation, which isn't allowed.

Then there is also an issue with /api/poi/{station} → List getPOIsByStation(String stationName) as it doesn't seem like the api is correctly hit when sent, if I remember correctly, but should be verified. Not sure what the issue is there.

**Comment by Nightwing52** [comment]
I will work on this soon. My plan is to encode the amenities by their ids separated by some special character.

Could you be more specific about the error you are getting?

**Comment by ZaneBartlett1** [comment]
It's just 
```
{
    "timestamp": "2023-05-25T21:41:22.106+00:00",
    "status": 400,
    "error": "Bad Request",
    "path": "/api/poi"
}
```

I have to assume it's because I'm trying to send a request body with a GET request and Java can't handle it.

**Comment by Nightwing52** [comment]
I got Docker working so tomorrow I should be able to resolve this issue.

**Comment by Nightwing52** [comment]
If the request is made without a response body I get your output. Note: it looks slightly different since #131).

![empty_request_body](https://github.com/DartExplore/dart-explore-backend/assets/18405628/a0e1984d-3379-4303-b2c4-153cdffbd3ab)

However, when I add the response body I get the correct output. Note: no amenity data has been added so the output is empty.

![non_empty_request_body](https://github.com/DartExplore/dart-explore-backend/assets/18405628/b14ea54d-c33b-41da-b461-7ab96b0e5608)

This is because as written the request body is mandatory. So I propose we change the mapping to allow for an empty response body and if we have an empty response body then we should return all points of interest. What do you think?
