### ISSUE TITLE
Improve exception handler.

### ISSUE THREAD

**Issue by Nightwing52** [DartExplore/dallas-by-metro-backend#210]
We need an exception handler for MissingServletRequestParameterException and find instances where we should be returning 404 instead of 400.

**Comment by ZaneBartlett1** [comment]
Could you give a couple examples of what you're talking about with this? I believe 400 request is accurate enough in most spots, since it's indicating that it's a bad request. 404 would mean that it can't find the resource, which I don't know what the context of that would be. - https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#client_error_responses

![image](https://github.com/DartExplore/dallas-by-metro-backend/assets/85081861/7548fe8e-f9a3-4378-8418-5ce1b95e83f9)

**Comment by Nightwing52** [comment]
For example, these errors should be returning 404 instead of 400:

![image](https://github.com/DartExplore/dallas-by-metro-backend/assets/18405628/8186785c-793d-449f-9452-995cad713be2)

These requests should keep returning 400.

![image](https://github.com/DartExplore/dallas-by-metro-backend/assets/18405628/63382414-d72b-49b1-8618-e4d8cb067da2)

**Comment by ZaneBartlett1** [comment]
That makes total sense to me, thanks for finding and fixing it!
